# Generated by Django 3.1.4 on 2021-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
