# Generated by Django 3.1.4 on 2021-01-02 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accepting_players', models.BooleanField(default=True)),
                ('beginners_welcome', models.BooleanField(default=True)),
                (
                    'campaign_type',
                    models.CharField(
                        choices=[
                            ('homebrew', 'Homebrew'),
                            ('modular', 'Modular'),
                            ('source-book', 'Campaign Source Book'),
                        ],
                        default='homebrew',
                        max_length=20,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mature_content', models.BooleanField(default=False, verbose_name='Contains mature content')),
                (
                    'max_players',
                    models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ('next_game_dt', models.DateTimeField(blank=True, null=True)),
                (
                    'price_per_session',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='The price per player per session.',
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    'role_play_level',
                    models.CharField(
                        choices=[('any', 'Any'), ('light', 'light'), ('heavy', 'heavy')], default='any', max_length=20
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Not started yet'),
                            ('cold', 'Gone cold'),
                            ('in-progress', 'In progress'),
                            ('finished', 'Finished'),
                        ],
                        default='pending',
                        editable=False,
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
