# Generated by Django 3.1.4 on 2020-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Not started yet'),
                            ('cold', 'Gone cold'),
                            ('in-progress', 'In progress'),
                            ('finished', 'Finished'),
                        ],
                        max_length=20,
                    ),
                ),
                ('max_players', models.IntegerField()),
            ],
        ),
    ]
