# Generated by Django 3.1.4 on 2020-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201208_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='accepting_players',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='beginners_welcome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(
                choices=[('homebrew', 'Homebrew'), ('modular', 'Modular'), ('source-book', 'Campaign Source Book')],
                default='homebrew',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mature_content',
            field=models.BooleanField(default=False, verbose_name='Contains mature content'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='next_game_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='price_per_session',
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text='The price per player per session.', max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='role_play_level',
            field=models.CharField(
                choices=[('any', 'Any'), ('light', 'light'), ('heavy', 'heavy')], default='any', max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Not started yet'),
                    ('cold', 'Gone cold'),
                    ('in-progress', 'In progress'),
                    ('finished', 'Finished'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
