# Generated by Django 3.1.4 on 2021-01-02 18:49

import easy_thumbnails.fields
from django.db import migrations

import DungeonFinder.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                null=True,
                storage=DungeonFinder.storage.FSPublicStorage(),
                upload_to='avatars',
                verbose_name='Avatar',
            ),
        ),
    ]
