# Generated by Django 3.1.4 on 2020-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_theme',
            field=models.CharField(blank=True, max_length=150, verbose_name='Theme'),
        ),
    ]
