# Generated by Django 3.1.4 on 2021-01-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_auto_20210102_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                (
                    'action_type',
                    models.IntegerField(
                        choices=[
                            (10, 'Logged in'),
                            (11, 'Logged out'),
                            (20, 'Joined a game'),
                            (21, 'Left a game'),
                            (30, 'Created a game'),
                            (31, 'Deleted a game'),
                            (32, 'Edited a game'),
                            (33, 'Kicked a player from a game'),
                            (40, 'Sent a message'),
                            (41, 'Deleted a message'),
                            (42, 'Edited a message'),
                        ],
                        db_index=True,
                    ),
                ),
                ('data', models.JSONField(null=True, blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    'target_campaign',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='actions',
                        to='games.campaign',
                    ),
                ),
                (
                    'target_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='actions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
