name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: waffle
        ports:
        - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: install dependencies
      run: |
        make install-dev
        make install-others
        pip freeze
    - name: lint
      run: make lint

    - name: test
      run: make test

    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 'bde83e7c-94e9-4b69-9c0e-f5815960f6b9'
